# .github/workflows/daily_signal.yml

name: Daily Hedging Signal

on:
  # Esegue lo script ogni giorno alle 07:00 UTC (09:00 ora italiana/greca in estate)
  schedule:
    - cron: '1 22 * * 0-4'
  
  # Permette di eseguire lo script manualmente dalla tab "Actions" di GitHub
  workflow_dispatch:

jobs:
  run-signal-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ===============================================================
      # === NUOVO STEP DI DEBUG - AGGIUNGI QUESTO BLOCCO ===
      - name: 4. List files in the repository
        run: ls -R
      # ===============================================================

      - name: 5. Create config.ini file
        run: |
          echo "[STRATEGY_PARAMS]" > config.ini
          # ... e il resto dello step ...
        
      - name: 6. Run the signal generation script
        env:
          PYTHONPATH: src
        run: python main.py
        
