# .github/workflows/daily_signal.yml

name: Daily Hedging Signal

on:
  schedule:
    - cron: '1 22 * * 0-5' # Esegue alle 22:01 UTC dalla Domenica al Giovedì
  
  workflow_dispatch:

jobs:
  run-signal-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: 4. Create config.ini file
        run: |
          echo "[STRATEGY_PARAMS]" > config.ini
          echo "capitale_iniziale = ${{ vars.CAPITALE_INIZIALE || '50000.00' }}" >> config.ini
          echo "hedge_percentage_per_tranche = ${{ vars.HEDGE_PERCENTAGE_PER_TRANCHE || '0.875' }}" >> config.ini
          echo "stop_loss_threshold_hedge = ${{ vars.STOP_LOSS_THRESHOLD_HEDGE || '0.05' }}" >> config.ini
          echo "micro_es_multiplier = ${{ vars.MICRO_ES_MULTIPLIER || '5' }}" >> config.ini
          echo "cmi_ma_window = ${{ vars.CMI_MA_WINDOW || '252' }}" >> config.ini
          echo "vix_ratio_upper_threshold = ${{ vars.VIX_RATIO_UPPER_THRESHOLD || '0.96' }}" >> config.ini
          echo "vix_ratio_lower_threshold = ${{ vars.VIX_RATIO_LOWER_THRESHOLD || '0.90' }}" >> config.ini
          echo "" >> config.ini
          echo "[TELEGRAM]" >> config.ini
          echo "bot_token = ${{ secrets.TELEGRAM_BOT_TOKEN }}" >> config.ini
          echo "chat_id = ${{ secrets.TELEGRAM_CHAT_ID }}" >> config.ini
          echo "" >> config.ini
          echo "[DATA]" >> config.ini
          echo "spy_ticker = SPY" >> config.ini
          echo "es_ticker = ES=F" >> config.ini
          echo "vix_ticker = ^VIX" >> config.ini
          echo "vix3m_ticker = ^VIX3M" >> config.ini
          echo "fred_series_cmi = { 'Yield_Curve_10Y2Y': 'T10Y2Y', 'VIX': 'VIXCLS', 'High_Yield_Spread': 'BAMLH0A0HYM2' }" >> config.ini

      - name: 5. Run the signal generation script
        run: python bot_runner.py
